### ISSUE TITLE
[Angular] guide/forms - section needs to be removed or reworked

### ISSUE THREAD

**Issue by TedSander** [dart-lang/site-webdev#114]
Please include URL: https://angulardart-org-dev.firebaseapp.com/angular/guide/forms

"The special CSS classes that ngControl adds to form controls and how to use them to provide strong visual feedback."

This section needs to be removed or reworked. We are deprecating NgControlStatus which is the entity which adds these special classes. It is deprecated because it adds 6 watchers to every model whether someone is using those classes or not.

The alternative is to set the values on the entity that you need yourself using ngClass or something similar.

**Comment by chalin** [comment]
> NgControlStatus ... is deprecated 
> **because it adds 6 watchers to _every_ model** 
> whether someone is using those classes or not.

@TedSander - so the main issue seems to be the "automatic" addition of the feature, not that the feature isn't useful, right? `NgControlStatus` has selectors `[ngControl],[ngModel],[ngFormControl]`, so why not change the selector(s) so that users can selectively activate this functionality if they want it (and are willing to pay the costs)?

cc @matanlurey @kwalrath

**Comment by TedSander** [comment]
So there are two issues:
a) The automatic nature
b) Adding 6 bindings that are generally not used. 

@ferhatb was actually the original person who pointed it out to me to be removed. I think I would generally like to see this pattern instead:
  `<input [(ngModel)]="model" [class.ng-valid]="control.valid" #control="ngForm"></input>`

Then you are explicit which classes you want, and what bindings. Then you aren't paying the price for codegen/bindings that you aren't using.

**Comment by chalin** [comment]
@TedSander - I see that under 3.0.0-alpha, `NgControlStatus` is marked as `@Deprecated`, but that it _still_ automatically applies to all the same selectors as before.

```dart
@Directive(selector: "[ngControl],[ngModel],[ngFormControl]", host: const {
  "[class.ng-untouched]": "ngClassUntouched",
  "[class.ng-touched]": "ngClassTouched",
  "[class.ng-pristine]": "ngClassPristine",
  "[class.ng-dirty]": "ngClassDirty",
  "[class.ng-valid]": "ngClassValid",
  "[class.ng-invalid]": "ngClassInvalid"
})
@Deprecated("Use listeners or variable binding on the control itself instead. "
    "This adds overhead for every form control whether the class is "
    "used or not.")
class NgControlStatus { ... }
```

I'm eager to make the update that you mention is this issue, but I'd rather wait until I can actually **_test_** my doc sample code. I can't do that until the selectors of `NgControlStatus` are removed (and maybe replaced with something like `[ngControlStatus]`.

Any objections to waiting, @TedSander, @ferhatb, @kwalrath?

The forms page is outdated in other respects. I've been reviewing the page and will submit a first round of updates shortly.

**Comment by TedSander** [comment]
It should no longer be in any of the default directives list. FORM_DIRECTIVES, CORE_DIRECTIVES, etc. So that selector should never match unless you specifically add it to your directives list.

So it should be possible to have an example without using this and having the code I linked above.

**Comment by chalin** [comment]
Ah, you are right. Ok, I'll put something together.

**Comment by chalin** [comment]
@TedSander - could you please take a look at the **two sections** of the staged _draft_ of the **forms** guide [starting at the _Track control state_ section](https://angulardart-org-dev.firebaseapp.com/angular/guide/forms#track-control-state). While I've rewritten the prose and example to illustrate how the user needs to set CSS classes manually, I've chosen to:

- Illustrate setting of a control element's CSS classes using the **`NgClass` directive** rather than using class bindings (in part because this is what is recommended in the [template syntax guide](http://localhost:4001/angular/guide/template-syntax#ngClass)):
    ```html
    <input [(ngModel)]="..." #name="ngForm" [ngClass]="controlStateClasses(name)">
    ```
- Continue to use the `ng-*` CSS class names, since other parts of the guide make reference to these names. But I do point out that the user is free to use any CSS class names in his/her app.

Will this address the concerns you raised in this issue?

**Comment by TedSander** [comment]
The link doesn't seem to work for me. Can you repost the link to the _draft_?

I'd rather not use NgClass in this example unless it is a lot more code. NgClass is a good deal less performant than [class.] syntax. Since this is one of the first documents the user will see I would rather start them down a better path.

We might need to update the NgClass documentation to lower the amount we are recommending it for now. It could possibly be made more performant, but it isn't a priority right now.

**Comment by chalin** [comment]
Strange, the link works for me (and I had someone else try it and it worked for them too). 

What might not be working is the proper scrolling to the appropriate section: but if your window is wide enough you should see a floating table of contents on the right - just select "Track control state"; here is the link to the draft: https://angulardart-org-dev.firebaseapp.com/angular/guide/forms

**Comment by chalin** [comment]
The issue with `NgClass` vs. class binding is that part of the forms example and accompanying prose illustrates all the control state changes using the CSS classes.

If you agree that the revised page is now _correct_ (though possibly not yet optimal), I'd suggest that we approve and merge it. We can then create a separate issue which will recommend use of class bindings over `NgClass` -- this would entail changes to _both_ the forms and template syntax pages). WDYT?

**Comment by TedSander** [comment]
Sure SGTM
