### ISSUE TITLE
Disallow search engines on every host other than webdev.dartlang.org

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#1457]
See https://www.google.com/search?q=site:webdev-dartlang-org-dev.firebaseapp.com

We don't want search engines wasting time with our dev domains.

We set this up with the package site. See https://dartlang-pub.appspot.com/robots.txt

Could we figure this out w/ our deploy script(s)?

**Comment by kwalrath** [comment]
This sounds like a job for @chalin...

I reckon we want to do the same for www.dartlang.org, as well.

**Comment by bcko** [comment]
I checked https://webdev-dartlang-org-dev.firebaseapp.com/robots.txt and the file says 
> All robots welcome!

Do you need to modify deploy script to change all dev domains robots.txt to 
```
User-agent: *
Disallow: /
```
?
Thank you

**Comment by bcko** [comment]
In src folder, both [_no-robots.txt](https://github.com/dart-lang/site-webdev/blob/master/src/_no-robots.txt
) and [robots.txt](https://github.com/dart-lang/site-webdev/blob/master/src/robots.txt) exist. 

In [firebase.sh](https://github.com/dart-lang/site-webdev/blob/master/scripts/deploy/firebase.sh), if bash variable $1 = '--robots-ok' then it allows robot to crawl otherwise it inserts _no-robots.txt contents for robots.txt to disallow crawling.

**Comment by chalin** [comment]
@kevmoo wrote:

> We don't want search engines wasting time with our dev domains.

We've been using webdev-dartlang-org-dev.firebaseapp.com to host Angular 5-dev docs since last fall. All updated docs (e.g., the `webdev` tool page) are only documented on the dev site. Are you sure that you don't want the dev site to be searchable?

---

@bcko: thanks for the feedback. There are some issues related to how Jekyll handles the robots files when doing incremental builds. The scripts that handle this will likely be placed in the shared repo so that both site-www and site-webdev will be handled uniformly. I'll be handling that as soon as I can.

**Comment by kwalrath** [comment]
@kevmoo, once we change webdev to be v5, the webdev-dartlang-org-dev links will be useless, and unfortunately Firebase doesn't give us a good way to forward those links.

**Comment by chalin** [comment]
To be clear, @kevmoo, you are ok with allowing the 5-dev site to be searched until we switch. Is that correct?

**Comment by kevmoo** [comment]
Yup!

**Comment by kwalrath** [comment]
OK, let's see how it goes.

**Comment by chalin** [comment]
Waiting on #1567
