### ISSUE TITLE
[master] examples/ng/doc/toh-6 term to results code is too complicated

### ISSUE THREAD

**Issue by gazialankus** [dart-lang/site-webdev#1626]
I spent some time trying to understand this piece of code in the tutorial: 
https://github.com/angular-examples/toh-6/blob/25ede633e4895b68d58b7fc382277837e74e32ce/lib/src/hero_search_component.dart#L36
```
        .transform(switchMap((term) => term.isEmpty
            ? new Stream<List<Hero>>.fromIterable([<Hero>[]])
            : _heroSearchService.search(term).asStream()))
```

This just gets a search term and returns the search results for that. However, it feels unnecessarily complicated. I would code it like this instead: 

```
        .asyncMap((term) => term.isEmpty
          ? new Future<List<Hero>>.value(<Hero>[])
          : _heroSearchService.search(term))
```

I tried this alternative version and it works fine. This has `asyncMap()` and `Future.value()` instead of `switchMap()`, `Stream.fromIterable()` or `Future.asStream()`. I belive this makes it easier to follow. Is there any reason why is it not coded in a simpler way like this? Would this be easier to understand for beginners reading this tutorial?

**Comment by chalin** [comment]
@gazialankus - it needs to be `switchMap()`. From the [docs](https://webdev-dartlang-org-dev.firebaseapp.com/angular/tutorial/toh-pt6#initialize-the-heroes-property-ngoninit):

> `transform(switchMap(...))` calls the search service for each
  search term that makes it through `debounce()` and `distinct()`.
  It cancels and discards previous searches, returning only the
  latest search service stream element.

The key part is that `switchMap()` **cancels and discards previous searches, returning only the latest search service stream element**.

Toh-6 doesn't use the network to fetch data, but let's suppose that it does. If you type "Ma" as a hero search term, this causes an HTTP request to be sent out. Suppose that you quickly complete the search term by typing "g" (so that the new search term is "Mag"). Then an new HTTP request is sent out. If the HTTP request for "Mag" completes before the one for "Ma", then the request for "Ma" will be discarded (since it is no longer relevant).

I hope that helps. SwitchMap can be difficult to understand if you aren't familiar with it: do a Google search for "why switch map" to find some more detailed explanations.
