### ISSUE TITLE
Delete 'Using Dart with JSON Web Services'

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#1634]
From URL: https://webdev.dartlang.org/articles/get-data/json-web-service

References https://pub.dartlang.org/packages/json_object – which hasn't been updated in 2+ years

Maybe update to use `json_serializable`?

**Comment by kevmoo** [comment]
CC @timsneath

**Comment by chalin** [comment]
Related: 

- Rework json-web-service article #864 - assigned to me
- The canonical JSON+Dart+Webapp article is referencing a probably-unmaintained library #526
- Clarify CORS headers in JSON article, fixing bug for Firefox #13

From #864:

- @Sfshaza wrote: This is a popular article full of useful info. As far as we know, it's not too out of date ...
- @kwalrath wrote: We approached Chris about an update but haven't heard from him, so it looks like we'll do the update ourselves. **We might rewrite it to fit into real docs**, somehow, **rather than being an article off to the side**.

If this is seen as a priority, I can move it towards the top of my list.

**Comment by kwalrath** [comment]
cc @matanlurey & @ferhatb, as this affects priorities for angular docs.

**Comment by kevmoo** [comment]
Re priority: angular docs first!

**Comment by chalin** [comment]
@kwalrath and I agreed that I can move ahead with updating the article, which shouldn't take too long. I won't make any major changes. The goal is mainly to refresh it so that it is Dart 2 compliant, and it uses the right support packages. If anyone has objections / comments to share before I start (not before tomorrow), let me know.

I've enabled "Watching" Andrew's https://github.com/RedBrogdon/jsonexample, so I'll get notified as soon as @RedBrogdon publishes some code.

**Comment by chalin** [comment]
@kevmoo et all:

Here is a brief review of related content across both sites:

- site-www:

  - A rather complete tutorial on how to **[Write HTTP Clients & Servers][]** (Dart VM).
    The tutorial illustrates how to send or process RESTful requests (in particular with **JSON data**); e.g., see [Making a POST request from a standalone client][].

  - [A Tour of the Dart Libraries](https://www.dartlang.org/guides/libraries/library-tour)
    This page has a section on [dart:convert - decoding and encoding JSON, UTF-8, and more][]. 

- site-webdev:

  - [AngularDart Tutorial, part 6: HTTP][] illustrates how an Angular app can interact with a RESTful backend with **JSON data**.

  - [A Tour of the dart:html Library][], which covers, among other things, [Using HTTP resources with HttpRequest][]. JSON is mentioned but no code examples are given.

Also note that @RedBrogdon is apparently working on [Flutter specific JSON examples](https://github.com/RedBrogdon/jsonexample).

Given the existing up-to-date content that we have, I'm not sure that the outdated "Using Dart with JSON Web Services" article brings anything new.

Thoughts?

> What about moving it to www?

Good question. Once we decide which content to keep (if any), it'll be easier to figure out where the page should reside.

[AngularDart Tutorial, part 6: HTTP]: https://webdev-dartlang-org-dev.firebaseapp.com/angular/tutorial/toh-pt6
[A Tour of the dart:html Library]: https://webdev-dartlang-org-dev.firebaseapp.com/guides/html-library-tour
[dart:convert - decoding and encoding JSON, UTF-8, and more]: https://www.dartlang.org/guides/libraries/library-tour#dartconvert---decoding-and-encoding-json-utf-8-and-more
[Write HTTP Clients & Servers]: https://www.dartlang.org/tutorials/dart-vm/httpserver
[Making a POST request from a standalone client]: https://www.dartlang.org/tutorials/dart-vm/httpserver#making-a-post-request-from-a-standalone-client
[Using HTTP resources with HttpRequest]: https://webdev-dartlang-org-dev.firebaseapp.com/guides/html-library-tour#using-http-resources-with-httprequest

**Comment by kwalrath** [comment]
After talking with @chalin, we're planning to delete this article and redirect to a new page, www.dartlang.org/guides/json or www.dartlang.org/guides/libraries/json, that'll link people to JSON resources.

Feedback, anyone? @kevmoo? @wmleler?

**Comment by Sfshaza** [comment]
I think that's preferable, since Flutter also uses JSON.

**Comment by kevmoo** [comment]
SGTM!

**Comment by chalin** [comment]
Great!

This issue will be for removing the article after https://github.com/dart-lang/site-www/issues/943 is completed.

**Comment by timsneath** [comment]
Splendid! Clean and concise!

On Jun 25, 2018, at 8:26 AM, Kathy Walrath <notifications@github.com<mailto:notifications@github.com>> wrote:


The new page is at https://www.dartlang.org/guides/json<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dartlang.org%2Fguides%2Fjson&data=02%7C01%7C%7Cb053cb5ae6a1451ae02708d5daaff3e4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636655371594316789&sdata=8kSxX3iX9kM7Zx7Awq4M8kjpXBpZ%2FThjdbi4jhwJiOE%3D&reserved=0>.

**Comment by kwalrath** [comment]
I think people are finding fetch-data useful. It's the 12th most popular landing page on webdev.dartlang.org, the most popular page under /tutorials/, and the 26th most popular page overall. Time on page is above average (3:55; average is 2:02), as are both the bounce rate and the exit rate, which I take to mean that people are finding what they need on this page.

So judging solely by the analytics, we should keep this page.
