### ISSUE TITLE
ACX codelab: feature ACX gallery earlier

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1771]
In https://github.com/dart-lang/site-webdev/pull/1769#pullrequestreview-144597193, @kwalrath wrote:

> I think (in a later PR) we should make the gallery a bigger part of this codelab. We could feature the gallery in the first page, and we could refer to it instead of the API docs when talking about a component.

**Comment by artem-galas** [comment]
@chalin Hm...That issue is quite interesting. 

I'll try to handle this if you provide some more detail what exactly we should do here.
Thanks.

**Comment by kwalrath** [comment]
Let's forget about focusing on the gallery in the first page, since it's already featured in Step 1.

What would be useful, though, is to change API references from generated API docs to gallery URLs. For example, at https://webdev.dartlang.org/codelabs/angular_components/2-starteasy#--use-material-progress, instead of linking to https://webdev.dartlang.org/api/angular_components/angular_components/MaterialProgressComponent-class, MaterialProgressComponent could link to https://dart-lang.github.io/angular_components/#/material_progress.
