### ISSUE TITLE
Redirect http://blog.angulardart.org/ to news.dartlang.org

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/site-webdev#192]

**Comment by kwalrath** [comment]
I've sent email to get this started.

**Comment by anders-sandholm** [comment]
Any responses to the email yet? Is this pending the improved hosting of angulardart.org in general?

**Comment by anders-sandholm** [comment]
Friendly ping. 
Now that the angulardart.org re-direct is super fast, can we fix this one too?

**Comment by kwalrath** [comment]
@filiph, what's the status?

**Comment by filiph** [comment]
Well, actually, we had to revert back to the old setup for now (because the new, Google setup doesn't have https yet, and some of our links are https, and when chrome sees that you've ever used a domain with https, it will default to that, so for such users the domain would be completely broken no matter what they click).

Anyways, we're still on the old setup and are waiting to get SSL at Google, at which point we'll switch and at which point the redirect will start working.

I'm glad to report the old setup has fixed the issue with multi-second lag. But of course we don't want to wait around until the issue reappears.

**Comment by anders-sandholm** [comment]
Ah, OK. 
Thanks for the update. 
Any idea of what an ETA to get SSL at Google might look like?

**Comment by chalin** [comment]
Closing since the redirect seems to be in place; try it out http://blog.angulardart.org.
