### ISSUE TITLE
Dead link in architecture section angular of guide

### ISSUE THREAD

**Issue by nemequ** [dart-lang/site-webdev#202]
https://webdev.dartlang.org/angular/guide/architecture has a link to https://webdev.dartlang.org/angular/guide/animations.html (in the "Wrap Up" section at the end), which doesn't exist.

The source seems to be [src/angular/_jade/ts/_cache/guide/architecture.jade#560](https://github.com/dart-lang/site-webdev/blob/4b7cd0bd8d0257a920bed6cafcaf806e68e1ebd3/src/angular/_jade/ts/_cache/guide/architecture.jade#L560).

**Comment by kwalrath** [comment]
Thanks very much for the report, @nemequ.

**Comment by chalin** [comment]
@kwalrath @kevmoo - this issue is an instance of a broader topic. Under ng.io, until the Dart version of a page was developed, we would often redirect curious readers to the TS version of the page. Shall we continue to do that here? We certainly don't want broken links so I see two immediately obvious approaches:

- Have a placeholder for each such page stating something like "under development".
- Continue to redirect eager readers to the TS page counterpart.

Any preferences or alternative suggestions?

**Comment by kwalrath** [comment]
I'm fine with linking eager readers to the TS page counterpart, as long as we know that it's truly relevant. If it isn't, then I'm inclined to have no page at all (or perhaps a placeholder if it's an obvious hole in our docs that we plan to fill soon).

**Comment by chalin** [comment]
Ok, #213 reverts to using the "see the corresponding TS page in the meantime" generic page.
