### ISSUE TITLE
in-page links scroll up to top

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#483]
I just noticed today that when I link to https://webdev.dartlang.org/guides/get-started#2-install-dart, the page starts out showing the section I want, but then scrolls up to the top.

This is in Chrome 59 canary, Chrome 56, and Safari 10.0.3.

It behaves fine in Firefox—great, even. It starts out below the header (and usual) and scrolls up just until you can see the section header. I suspect that's what used to happen in Chrome/Safari.

Same thing happens in other webdev pages:
https://webdev.dartlang.org/codelabs/angular2_components/2-easystart#--set-up-the-root-components-dart-file

However, www is fine (which makes me wonder if this is related to Angular CSS changes):
https://www.dartlang.org/guides/language/language-tour#operators

Angular pages are even more broken, not even starting at the section header, as reported in #315.

cc @filiph @chalin

**Comment by chalin** [comment]
Ah it seems that we've hit this problem before. It works for site-www because @filiph disabled the [problematic code](https://github.com/dart-lang/site-www/blob/master/src/_assets/javascripts/main.js#L81-L101) back in October :)

I'll briefly investigate if I can fix it; otherwise I'll just disable it (as was done for site-www).

**Comment by kwalrath** [comment]
Ah, another case where sharing the implementation, rather than duplicating it, would've helped us.

**Comment by chalin** [comment]
Yes
