### ISSUE TITLE
Update angular_components API docs to 0.5.2

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#674]
/cc @nshahan

**Comment by kwalrath** [comment]
We also need to have a better process, so there won't be as much of a delay when new docs need to be generated.

**Comment by nshahan** [comment]
Is there a consensus on what locations (docs, examples, etc) we want to update every time there is new release, no matter how minor?

If we at least identify those locations I can send PRs when I publish a new releases.

**Comment by kwalrath** [comment]
@nshahan: A PR or issue in this repo would be great, either one.

@chalin, do we want to update everything under /angular and /components on webdev every time angular2 or angular_components has a new stable release? We also need to update webdev.dartlang.org/angular/version whenever either of those packages has a dev release.

@nshahan: We need a heads up if there's a reason why stuff that we wouldn't usually update for minor releases (stagehand, codelabs, etc.) should update its required version (and any other code). An PR/issue on https://github.com/google/stagehand would be sufficient notification for that.

**Comment by chalin** [comment]
> do we want to update everything under /angular and /components on webdev every time angular2 or angular_components has a new stable release?

The site builds the API docs for the named releases, so the release numbers need to be changed every time. Whether we update the package versions in the example pubspecs is a separate issue. I like to bump up the numbers just because it makes it obvious which versions our examples are running (and being tested) under.

> We also need to update webdev.dartlang.org/angular/version whenever either of those packages has a dev release.

The `version` page makes use of variables defined in `_config.yml`, and so we need only update the latter.
