### ISSUE TITLE
In Angular API reference, be clear about what import to use.

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#787]
FIXED this part:
> For example, when you go to the AngularDart API homepage (https://webdev.dartlang.org/angular/api), it doesn't say what you should import to get the APIs listed under angular2.common._

This info should be—at the very least— on both on https://webdev.dartlang.org/angular/api and the individual library page (in this case, https://webdev.dartlang.org/angular/api/angular2.compiler/angular2.compiler-library). You can't get to the library page from the API homepage, but you can get there by clicking the library name in the header.

Strangely, once you do that, "angular2.common" is crossed out in the header and left nav, which makes it look like it's deprecated. How can the first library in the API page be deprecated?!

**Comment by chalin** [comment]
FYI, [`angular.common` is gone as of `4.0.0-alpha+1`](https://github.com/dart-lang/angular/commit/6e55e2666207f96634290ffbb97b7932be3a3597#diff-1f554f358a75ba206c49542dd0c50aabR45).

**Comment by chalin** [comment]
There have been considerable improvements made to dartdoc recently (thanks @jcollins-g!). In particular, canonical reference resolution. Because of these improvements, and because (as of 4.x) our API page will be showing `angular` package entries (which we used to hide to avoid duplicates), I believe that the issue reported here has essentially been resolved.

For a preview of the 4.x API page see https://webdev-dartlang-org-dev.firebaseapp.com/angular/api.

I believe that this issue has been resolved in that, for any given symbol X appearing under the package grouping P, one would need to `import 'package:angular/P.dart`.

Given this general rule, we could add a note to this effect on the API page, or put the import statement as a hover/tool-tip anchored on the package name, ... .  

Kathy, WDYT?

**Comment by kwalrath** [comment]
I'd like to have the import statements explicitly in this page (and elsewhere, if possible), since hover/tooltips aren't good for mobile, and the clearer we can make this doc, the better. Let's keep this issue open until we have visible help on importing.

I'll file issues for the other problems I've noticed in our API docs.

**Comment by chalin** [comment]
Here is a proposal for showing imports on the API homepage (I'm only showing Functions so that you can see multiple groups -- note that the group heading can be a link to the library dartdoc API page):
> ![screen shot 2017-07-21 at 5 53 10 pm](https://user-images.githubusercontent.com/4140793/28483899-8c56592a-6e3d-11e7-9ff5-b43d481a1fe0.png)

> ![screen shot 2017-07-21 at 5 53 30 pm](https://user-images.githubusercontent.com/4140793/28483905-953f7710-6e3d-11e7-962f-2a2c60d187df.png)

**Comment by kwalrath** [comment]
I like it!

**Comment by chalin** [comment]
@kwalrath, can we consider this issue closed (even if we don't have the import info on each and every page)?

**Comment by kwalrath** [comment]
Sure. I'll open a bug on dart-lang/angular to add import info to each library's description.
