### ISSUE TITLE
[ng] Changelog for documentation and examples?

### ISSUE THREAD

**Issue by Janamou** [dart-lang/site-webdev#856]
Hi,

I had really hard times with porting my older Angular code today. And the reason is that there are big changes in the latest versions of Angular but there is no information about all of them (I know that there is this: https://pub.dartlang.org/packages/angular2#pub-pkg-tab-changelog but not everything is there - and specifically things I had to solve).

What about having some page where will be written all changes you have done in the source code of examples? I think this would help a lot with porting also our code.

My problem was the change in directives (e.g. that the constants need to be explicitly mentioned in components now) but this change was not written anywhere. And also the change in imports from angular2/core.dart to angular2/angular2.dart.

I dont have time to read Gitter...

**Comment by chalin** [comment]
The ng TS docs used to have a docs specific changelog, but it was dropped. It may have been because there was too much duplication.

I think that a solution might be to enhance the Angular changelog.
@matanlurey, @kwalrath WDYT?

**Comment by kwalrath** [comment]
Some of the changes might not be angular-specific (e.g. lib -> lib/src). Maybe we could add something to our Version page about changes we made for each version?

**Comment by kwalrath** [comment]
I'll be happy to mock something up for this.

**Comment by kwalrath** [comment]
@Janamou how about something like this:

## Changelog

This changelog summarizes changes to the AngularDart docs and examples that might help you update your own code. Many of these changes coincide with new releases of AngularDart, AngularDart Components, or the Dart SDK; others are the result of new recommendations.

To see all changes to the docs and examples, go to the site-webdev repo on GitHub:

* [History for site-webdev/src/angular](https://github.com/dart-lang/site-webdev/commits/master/src/angular)
* [History for site-webdev/examples/ng/doc](https://github.com/dart-lang/site-webdev/commits/master/examples/ng/doc)


### AngularDart 4.0-alpha

All pubspecs and imports changed, due to the `angular2` package changing its name to `angular`. The removal of `common.dart` didn't affect our code, but we had to adjust the API doc generation. If your code imports `angular2/common.dart`, use `angular/angular.dart` instead.

* Updated references to packages and transformers in `pubspec.yaml`:
  * `angular2` &rarr; `angular`
  * `^3.1.0` &rarr; `^4.0.0-alpha`
* Changed imports:
    * `angular2/angular2.dart` &rarr; `angular/angular.dart`
    * `angular2/platform/browser.dart` &rarr; `angular/angular.dart`
      [PENDING: why?]
* Updated API doc generation, with the following effects on URLs:
  * angular2.common &rarr; angular2 &rarr; angular
    (example: Control before & after URLs)
  * angular2.core &rarr; angular.core
    (example: Component before & after URLs)
  * ...

More information:

* [angular changelog](https://pub.dartlang.org/packages/angular#pub-pkg-tab-changelog)
* [History for site-webdev/examples/ng (4-dev branch)](https://github.com/dart-lang/site-webdev/commits/4-dev/examples/ng)
* [...relevant PRs...]


### Dart 1.24

The examples changed to use the Dart development compiler (dartdevc) by default during development.

* Moved most implementation Dart files under `lib/src/*`,  instead of `lib/*`.
* Updated `pubspec.yaml` to make dartdevc the default development compiler.

More information:
* [Preparing your code](/tools/dartdevc#preparing-your-code) in the [dartdevc documentation](/tools/dartdevc)
* [Dart 1.24 announcement](http://news.dartlang.org/2017/06/dart-124-faster-edit-refresh-cycle-on.html)
* [PR 744](https://github.com/dart-lang/site-webdev/pull/744/files) and other ["src reorg" PRs](https://github.com/dart-lang/site-webdev/pulls?utf8=%E2%9C%93&q=is%3Apr%20%22src%20reorg%22)
* [PR 684](https://github.com/dart-lang/site-webdev/pull/684/files)


### AngularDart 3.1

The examples changed to update the release and reflect new recommendations.

* Changed `core.dart` imports to `angular2.dart`.
* To prepare for 3.1's experimental compiler, in each example:
  * Removed `platform_directives` from `pubspec.yaml`, moving the directives it listed
    to the relevant components' `directives` lists.
  * Removed `platform_pipes` from `pubspec.yaml`, moving the pipes it listed
    to the relevant components' `pipes` lists.
* Updated the `angular2` dependency in each example's pubspec:
  `^3.0.0` &rarr; `^3.1.0`.

More information:

* [angular2 changelog](https://pub.dartlang.org/packages/angular2#pub-pkg-tab-changelog)
* [PR #625](https://github.com/dart-lang/site-webdev/pull/625/files?w=1)
* [...relevant PRs...]

**Comment by Janamou** [comment]
@kwalrath thank you, looks nice. Only thing I am still missing is the note about _DIRECTIVES (COMMON_DIRECTIVES, FORM_DIRECTIVES etc.) and _PIPES which now have to be explicitly mentioned in the components. Its visible in changes: https://github.com/dart-lang/site-webdev/pull/625/files?w=1 but its not explicitly mentioned in changelog...
