### ISSUE TITLE
Update Angular API documentation for 4.0.0-alpha+2

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/site-webdev#913]
* https://webdev.dartlang.org/angular/version says `4.0.0-alpha`
* [Staging site](https://webdev-dartlang-org-dev.firebaseapp.com/angular/guide) is `4.0.0-alpha+1`

**Comment by chalin** [comment]
The staging site will be updated as soon as https://github.com/dart-lang/site-webdev/pull/910 is merged. I haven't done that yet because angular_tests aren't passing for any of the examples -- see https://github.com/dart-lang/angular/issues/574

Once the staging site has been updated to alpha+2 I'll also update the main site.

**Comment by matanlurey** [comment]
No worries, just filing a tracking bug! Thanks!
